export const REGISTER_REQUEST   = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS   = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE   = 'REGISTER_FAILURE'

export const LOGIN_REQUEST   = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS   = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE   = 'LOGIN_FAILURE'

export const GET_USER_REQUEST   = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS   = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE   = 'GET_USER_FAILURE'

export const LOGOUT = 'LOGOUT'
export const SET_ERROR_NULL = 'SET_ERROR_NULL'

export const UPDATE_USER_REQUEST   = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS   = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE   = 'UPDATE_USER_FAILURE'

export const CHANGE_PASSWORD_REQUEST   = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS   = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE   = 'CHANGE_PASSWORD_FAILURE'

export const FORGOT_PASSWORD_RRQUEST = 'FORGOT_PASSWORD_RRQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE' 

export const RESET_PASSWORD_RRQUEST = 'RESET_PASSWORD_RRQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE' 