export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE'

export const CONFIRMED_ORDERS_REQUEST = 'CONFIRMED_ORDERS_REQUEST'
export const CONFIRMED_ORDERS_SUCCESS = 'CONFIRMED_ORDERS_SUCCESS'
export const CONFIRMED_ORDERS_FAILURE = 'CONFIRMED_ORDERS_FAILURE'

export const PLACED_ORDERS_REQUEST = 'PLACED_ORDERS_REQUEST'
export const PLACED_ORDERS_SUCCESS = 'PLACED_ORDERS_SUCCESS'
export const PLACED_ORDERS_FAILURE = 'PLACED_ORDERS_FAILURE'

export const DELIVERED_ORDERS_REQUEST = 'DELIVERED_ORDERS_REQUEST'
export const DELIVERED_ORDERS_SUCCESS = 'DELIVERED_ORDERS_SUCCESS'
export const DELIVERED_ORDERS_FAILURE = 'DELIVERED_ORDERS_FAILURE'

export const CANCELLED_ORDERS_REQUEST = 'CANCELLED_ORDERS_REQUEST'
export const CANCELLED_ORDERS_SUCCESS = 'CANCELLED_ORDERS_SUCCESS'
export const CANCELLED_ORDERS_FAILURE = 'CANCELLED_ORDERS_FAILURE'

export const SHIPPED_ORDERS_REQUEST = 'SHIPPED_ORDERS_REQUEST'
export const SHIPPED_ORDERS_SUCCESS = 'SHIPPED_ORDERS_SUCCESS'
export const SHIPPED_ORDERS_FAILURE = 'SHIPPED_ORDERS_FAILURE'

export const DELETE_ORDERS_REQUEST = 'DELETE_ORDERS_REQUEST'
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS'
export const DELETE_ORDERS_FAILURE = 'DELETE_ORDERS_FAILURE'